### PR TITLE
Add Swagger for the WebAPI

### LINKED ISSUE #107: Add Swagger
## Is your feature request related to a problem? Please describe:
Currently, the API is not documented.

## Describe the solution you'd like:
Add Swagger and an OpenAPI spec for better documentation of the API.

We can use https://github.com/swaggo/gin-swagger for that purpose.

### PR DESCRIPTION
**Pull request by pascal-zarrad**
## Description
Add `gin-swagger` and configure it to provide a Swagger by default.

## Open ToDos
For ToDos, see https://github.com/swaggo/swag/blob/master/README.md#how-to-use-it-with-gin for some information about defining meta.

- [x] Add general API meta
- [x] Add documentation to stats endpoint
- [x] Add documentation to components endpoint
- [x] Refactor some API core code and reduce redundancies in statistics component
- [x] Atomate generation of OpenAPI spec

## Related issue
Resolves #107 

## How can this be tested?
Check the route `/swagger` on the web api.

### CODE REVIEW

**Review by elias-knodel — COMMENTED** [review]
Review looks good as far as i can see. Now i just need to test it.

**Review by elias-knodel — CHANGES_REQUESTED** [review]
The files don't get generated correctly. `info.version` and `info.title` are missing.

For an example, see: https://github.com/swaggo/gin-swagger/blob/c8d47d5b4ae92c018b2abb089ad499ae30d98664/example/basic/main.go#L13-L14

**Comment by pascal-zarrad** [comment]
> The files don't get generated correctly. `info.version` and `info.title` are missing.
> 
> For an example, see: https://github.com/swaggo/gin-swagger/blob/c8d47d5b4ae92c018b2abb089ad499ae30d98664/example/basic/main.go#L13-L14

While we can jsut define the title properly this won't be easy or possible for version, as we dynamically set the version during build time. We need to evaluate how we could deal with that.

**Comment by pascal-zarrad** [comment]
Version will be just pinned to 1.0.0 in the `docs.json` and `docs.yaml` for now. We will see in the future if we can keep those values in sync with the bots version.

**Review by elias-knodel — APPROVED** [review]
LGTM :+1:

**Pull request merged**
